databases:
 - name: metalink
   databaseName: metalink
   user: metalink

services:
 - type: web
   name: metalink
   env: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn metalink.wsgi:application"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: metalink
         property: connectionString
     - key: SECRET_KEY
       generateValue: true
     - key: WEB_CONCURRENCY
       value: 4
